GET http://localhost:3009/players/
###
GET http://localhost:3009/players/2/
###
PUT http://localhost:3009/players/3/
Content-Type: application/json  

{
     "playerName": "Raju"
}
###
GET http://localhost:3009/matches/18/
###
GET http://localhost:3009/players/2/matches
###
GET http://localhost:3009/matches/2/players
###
GET http://localhost:3009/players/1/playerScores